# The name of your Flutter application/project.
name: flutter_application_krushnesh

# A short description of your app.
description: A new Flutter project.

# This prevents the app from being published to pub.dev (use 'none' for private apps).
publish_to: 'none'

# The version of your app (versionCode+versionName for Android).
version: 1.0.0+1

# The Dart SDK version required to run this app.
environment:
  sdk: ">=3.8.0 <4.0.0"

# ----------------------------
# Project dependencies
# ----------------------------
dependencies:
  flutter:
    sdk: flutter

  # State management and routing
  get: ^4.7.2

  # HTTP package for API calls
  http: ^1.4.0

  # Local storage
  shared_preferences: ^2.2.2

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # YouTube plugin (ensure it's maintained and works well)
  youtube: ^2.0.0
 
  # For video playback
  video_player: ^2.10.0

# ----------------------------
# Development-only dependencies
# ----------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting best practices
  flutter_lints: ^3.0.1

  # Launcher icon generator
  flutter_launcher_icons: ^0.14.4

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/Youtube_logo.png"
  min_sdk_android: 21

# ----------------------------
# Flutter-specific configuration
# ----------------------------
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/Youtube_logo.png
